POST http://localhost:3000/reports/create-report
Content-Type: application/json

{
    "make": "Ford",
    "model": "Mustang",
    "year": 1982,
    "mileage": 50000,
    "longtitude": 45,
    "latitude": 45,
    "price": 20000
}

###
PATCH http://localhost:3000/reports/17
Content-Type: application/json

{
    "approved": true
}

###
GET http://localhost:3000/reports?make=Ford&model=Mustang&year=1981&mileage=20000&longtitude=45&latitude=45